# -*- coding: utf-8 -*-
"""train_intent_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5YpTubr63LG2o4z38FRD6IV8w0Y4LV1
"""

import os
import joblib
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    ConfusionMatrixDisplay,
)

from preprocess import clean_text

TRAIN_PATH = "data/processed/clinc_subset_train.csv"
VAL_PATH = "data/processed/clinc_subset_val.csv"
TEST_PATH = "data/processed/clinc_subset_test.csv"

RESULTS_DIR = "results"
MODELS_DIR = "models"

MODEL_PATH = os.path.join(MODELS_DIR, "intent_classifier.pkl")


def ensure_dirs():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    os.makedirs(MODELS_DIR, exist_ok=True)


def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df = df.dropna(subset=["text", "intent"]).copy()
    df["text"] = df["text"].apply(clean_text)
    return df


def build_pipeline() -> Pipeline:
    return Pipeline([
        ("tfidf", TfidfVectorizer(ngram_range=(1, 2))),
        ("clf", LogisticRegression(max_iter=1000, random_state=42))
    ])


# 🔥 YENİ: threshold ile tahmin
def predict_with_threshold(model, texts, threshold=0.5):
    probs = model.predict_proba(texts)
    classes = model.classes_

    preds = []
    for row in probs:
        max_idx = row.argmax()
        max_prob = row[max_idx]
        pred = classes[max_idx]

        if max_prob < threshold:
            preds.append("oos")
        else:
            preds.append(pred)

    return preds


def evaluate(name, y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)
    report = classification_report(y_true, y_pred, digits=4)

    print(f"\n=== {name} ===")
    print(f"Accuracy: {acc:.4f}")
    print(report)

    return acc, report


def save_confusion_matrix(y_true, y_pred, filename):
    labels = sorted(set(y_true))
    fig, ax = plt.subplots(figsize=(8, 8))
    ConfusionMatrixDisplay.from_predictions(
        y_true,
        y_pred,
        display_labels=labels,
        xticks_rotation=45,
        ax=ax,
    )
    plt.tight_layout()
    plt.savefig(os.path.join(RESULTS_DIR, filename), dpi=200)
    plt.close()


def main():
    ensure_dirs()

    train_df = load_data(TRAIN_PATH)
    val_df = load_data(VAL_PATH)
    test_df = load_data(TEST_PATH)

    model = build_pipeline()
    model.fit(train_df["text"], train_df["intent"])

    # 🔹 Normal prediction
    val_pred = model.predict(val_df["text"])
    test_pred = model.predict(test_df["text"])

    # 🔹 Threshold prediction
    THRESHOLD = 0.5
    val_pred_th = predict_with_threshold(model, val_df["text"], THRESHOLD)
    test_pred_th = predict_with_threshold(model, test_df["text"], THRESHOLD)

    # 🔹 Evaluation
    val_acc, val_report = evaluate("Validation (Normal)", val_df["intent"], val_pred)
    test_acc, test_report = evaluate("Test (Normal)", test_df["intent"], test_pred)

    val_acc_th, val_report_th = evaluate("Validation (Threshold)", val_df["intent"], val_pred_th)
    test_acc_th, test_report_th = evaluate("Test (Threshold)", test_df["intent"], test_pred_th)

    # 🔹 Save metrics
    with open(os.path.join(RESULTS_DIR, "metrics.txt"), "w", encoding="utf-8") as f:
        f.write("=== NORMAL MODEL ===\n")
        f.write(f"Validation Accuracy: {val_acc:.4f}\n")
        f.write(f"Test Accuracy: {test_acc:.4f}\n\n")
        f.write(val_report)
        f.write("\n\n")
        f.write(test_report)

        f.write("\n\n=== THRESHOLD MODEL ===\n")
        f.write(f"Validation Accuracy: {val_acc_th:.4f}\n")
        f.write(f"Test Accuracy: {test_acc_th:.4f}\n\n")
        f.write(val_report_th)
        f.write("\n\n")
        f.write(test_report_th)

    # 🔹 Save confusion matrices
    save_confusion_matrix(test_df["intent"], test_pred, "confusion_matrix_normal.png")
    save_confusion_matrix(test_df["intent"], test_pred_th, "confusion_matrix_threshold.png")

    # 🔹 Save model
    joblib.dump(model, MODEL_PATH)

    print("\nModel saved.")
    print("Results saved in /results")


if __name__ == "__main__":
    main()